In [1]:
# We begin by importing the essentials
import numpy as np
from sklearn.model_selection import train_test_split

# bounded gLV with randomized background

## N=100 community

### split the randomized initial conditions for 10K simulations

In [2]:
n_ori=100

glv_type="b"
model_index=1

NT=[1,4,6,7,9]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    X=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_random_init.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, ))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_random_init_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_random_init_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, ),X_test)

(8000, 100) (2000, 100)
[0.09445131] [0.18903515]
(8000, 100) (2000, 100)
[0.01170116 0.12844116 0.0954623  0.14487186] [0.14238973 0.141626   0.062659   0.07620388]
(8000, 100) (2000, 100)
[0.05516056 0.06002399 0.09402889 0.07146665 0.05198558 0.03742435] [0.0059423  0.14659123 0.16513521 0.12724049 0.07390928 0.10272665]
(8000, 100) (2000, 100)
[0.05365599 0.17828014 0.1888067  0.10112128 0.12676094 0.08977752
 0.0959192 ] [0.13625043 0.18044115 0.01400159 0.04985157 0.0862781  0.18123892
 0.03704735]
(8000, 100) (2000, 100)
[0.19140828 0.11453037 0.15792389 0.06688101 0.17791763 0.1144675
 0.19777335 0.16958098 0.04561319] [0.16768582 0.08802907 0.1634763  0.1258692  0.05457325 0.05340407
 0.05545548 0.01567982 0.12522327]


In [17]:
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_random.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    Y=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        Y.append(data)
    Y=np.array(Y)

    Y_train, Y_test = train_test_split(Y, test_size=0.2, random_state=42)
    print(Y_train.shape)
    print(Y_train[0,:,0],Y_test[0,:,0])

(8000, 2, 50)
[0.04899643 0.02775842] [0.07429575 0.13061159]
(8000, 3, 50)
[0.15735079 0.18118422 0.04617403] [0.02566623 0.17631538 0.00998976]
(8000, 5, 50)
[0.09309838 0.1093366  0.02152618 0.04824542 0.03000666] [0.10683064 0.06080269 0.0435894  0.11632915 0.11933115]
(8000, 8, 50)
[0.16411661 0.00076337 0.15961046 0.05133188 0.06265708 0.16352573
 0.07074129 0.06888546] [0.17705125 0.1279113  0.03865693 0.118476   0.13797878 0.1286088
 0.19842839 0.0864464 ]
(8000, 10, 50)
[0.1264277  0.14129988 0.18651075 0.12435549 0.15695356 0.12524201
 0.0592731  0.08961235 0.033642   0.02059219] [0.00475079 0.13266504 0.09740286 0.14747764 0.01528164 0.02046706
 0.00047971 0.05301371 0.01959868 0.16170184]


### split the simulated time series

In [5]:
n_ori=100

glv_type="b"
sim_type="random"
model_index=3

NT=[1,4,6,7,9,]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    X=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        X.append(data)
    X=np.array(X)

    xmax = np.max(X)
    print(xmax)
    X = X/xmax
    print(np.max(X))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

0.215615613769582
1.0
0.265597488750085
1.0
0.273485976622669
1.0
0.261790950252854
1.0
0.2803208489088
1.0


### split the second dataset of 100K simulations

In [7]:
n_ori=100

glv_type="b"
sim_type="random"
model_index=1

X=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_random_init_100K.txt"
                           % (glv_type, model_index, glv_type))

X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
np.save("./saved_sims/%sgLV/I%i/%sgLV_random_init_train_100K.npy"
                           % (glv_type, model_index, glv_type),X_train)
np.save("./saved_sims/%sgLV/I%i/%sgLV_random_init_test_100K.npy"
                           % (glv_type, model_index, glv_type),X_test)

NT=[2,3,5,8,10,]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_100K.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    X=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        X.append(data)
    X=np.array(X)

    xmax = np.max(X)
    print(xmax)
    X = X/xmax
    print(np.max(X))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train_100K.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test_100K.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

0.316585240140106
1.0
0.316585240140106
1.0
0.316585240140106
1.0
0.400671472391139
1.0
0.400671472391139
1.0


## Community with stronger interactions

In [10]:
n_ori=100

glv_type="b"
sim_type="random"
model_index=7

n_target=10
n_background=n_ori-n_target
original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                           % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
ts_length = original_data.shape[1]

N_Sample = int(original_data.shape[0]/n_target)
X=[]
for i in range(N_Sample):
    data=original_data[i*n_target:(i+1)*n_target,:]
    X.append(data)
X=np.array(X)

for n_target in np.arange(1,11,1):
    n_background = n_ori-n_target
    X_save = X[:,0:n_target,:]
    xmax = np.max(X_save)
    print(xmax)
    X_save = X_save/xmax
    print(np.max(X_save))
    X_train, X_test = train_test_split(X_save, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

0.199967209083496
1.0
0.199988080896541
1.0
0.199996317892988
1.0
0.199996987804019
1.0
0.199998775108858
1.0
0.199998775108858
1.0
0.199998775108858
1.0
0.199998775108858
1.0
0.199998775108858
1.0
0.254840324660837
1.0


## N=10 community

### split the randomized initial conditions

In [4]:
n_ori=10

glv_type="b"
model_index=6

X=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_random_init.txt"
                           % (glv_type, model_index, glv_type))

X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
print(X_train.shape,X_test.shape)
np.save("./saved_sims/%sgLV/I%i/%sgLV_random_init_train.npy"
                           % (glv_type, model_index, glv_type),X_train)
np.save("./saved_sims/%sgLV/I%i/%sgLV_random_init_test.npy"
                           % (glv_type, model_index, glv_type),X_test)

(8000, 10) (2000, 10)


In [20]:
n_target=2
n_background=n_ori-n_target
original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_random.txt"
                           % (glv_type, model_index, glv_type, n_background, n_target))
ts_length = original_data.shape[1]

N_Sample = int(original_data.shape[0]/n_target)
Y=[]
for i in range(N_Sample):
    data=original_data[i*n_target:(i+1)*n_target,:]
    Y.append(data)
Y=np.array(Y)

Y_train, Y_test = train_test_split(Y, test_size=0.2, random_state=42)
print(Y_train.shape)
print(Y_train[0,:,0],Y_test[0,:,0])

(8000, 2, 50)
[0.15764262 0.06807733] [0.04015985 0.102542  ]


### split the simulated time series

In [14]:
n_ori=10

glv_type="b"
sim_type="random"
model_index=6

NT=[2,3,5,8,10,]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    X=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        X.append(data)
    X=np.array(X)

    xmax = np.max(X)
    print(xmax)
    X = X/xmax
    print(np.max(X))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

0.683101538338469
1.0
0.683101538338469
1.0
0.683101538338469
1.0
0.683101538338469
1.0
0.683101538338469
1.0


In [4]:
n_ori=10

glv_type="b"
sim_type="random"
model_index=6

n_target=10
n_background=n_ori-n_target
original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                           % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
ts_length = original_data.shape[1]

N_Sample = int(original_data.shape[0]/n_target)
X=[]
for i in range(N_Sample):
    data=original_data[i*n_target:(i+1)*n_target,:]
    X.append(data)
X=np.array(X)

for n_target in [1,4,6,7,9]:
    n_background = n_ori-n_target
    X_save = X[:,0:n_target,:]
    X_train, X_test = train_test_split(X_save, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

# bounded gLV with fixed background

In [8]:
n_ori=100

glv_type="b"
sim_type="fixed"
model_index=3

NT=[4,6,7,9,]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    X=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        X.append(data)
    X=np.array(X)
    
    xmax = np.max(X)
    print(xmax)
    X = X/xmax
    print(np.max(X))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

0.199998275907939
1.0
0.19999516517063
1.0
0.1999998405718
1.0
0.21499231429209
1.0


# spatial gLV

In [20]:
n_ori=100

glv_type="s"
sim_type="fixed"
model_index=3

NT=[2,3,5,9,]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    X=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        X.append(data)
    X=np.array(X)

    xmax = np.max(X)
    print(xmax)
    X = X/xmax
    print(np.max(X))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

1.9997365614455442
1.0
1.999978605560611
1.0
1.9995430193796109
1.0
1.9999058662136444
1.0


# dispersal gLV

In [8]:
n_ori=100

glv_type="d"
sim_type="fixed"
model_index=3

NT=[1,4,6,7]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    X=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        X.append(data)
    X=np.array(X)

    xmax = np.max(X)
    print(xmax)
    X = X/xmax
    print(np.max(X))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

0.292507277836658
1.0
0.459681981442357
1.0
0.736470882585783
1.0
0.739214689980523
1.0


### create simulations with target sizes of 1,4,6,7

In [5]:
n_ori=100

glv_type="d"
sim_type="random"
model_index=3

n_target=8
n_background=n_ori-n_target
original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                           % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
ts_length = original_data.shape[1]

N_Sample = int(original_data.shape[0]/n_target)
X=[]
for i in range(N_Sample):
    data=original_data[i*n_target:(i+1)*n_target,:]
    X.append(data)
X=np.array(X)

for n_target in [1,4,6,7]:
    n_background = n_ori-n_target
    X_save = X[:,0:n_target,:]
    X_train, X_test = train_test_split(X_save, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

In [5]:
n_ori=100

glv_type="d"
sim_type="random"
model_index=3

NT=[2,3,5,8,]
for i in range(len(NT)):
    n_target=NT[i]
    n_background=n_ori-n_target
    original_data=np.loadtxt("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s.txt"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ))
    ts_length = original_data.shape[1]

    N_Sample = int(original_data.shape[0]/n_target)
    X=[]
    for i in range(N_Sample):
        data=original_data[i*n_target:(i+1)*n_target,:]
        X.append(data)
    X=np.array(X)

    xmax = np.max(X)
    print(xmax)
    X = X/xmax

    print(X.shape)

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B%i_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_background, n_target, sim_type, ),X_test)

0.759076647971015
(100000, 2, 50)
0.759076647971015
(100000, 3, 50)
0.759076647971015
(100000, 5, 50)
0.7915064122508
(100000, 8, 50)


# plasmid dynamics

In [23]:
n_ori=100
glv_type="p"
sim_type="fixed"
model_index=3
NT=[2,3,4,5,]
for i in range(len(NT)):
    n_target=NT[i]
    X = np.load("/hpc/group/youlab/zz294/VAE/saved_sims/pgLV/I%i/pcf_simulation_results_100_species_5_plasmids_replicate_%i_%i_targets.npy"
                               % (model_index, model_index, n_target, ))
    X = X[:,:-1,:]

    xmax = np.max(X)
    print(xmax)
    X = X/xmax
    print(np.max(X))

    X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B100_T%i_%s_train.npy"
                               % (glv_type, model_index, glv_type, n_target, sim_type, ),X_train)
    np.save("./saved_sims/%sgLV/I%i/%sgLV_B100_T%i_%s_test.npy"
                               % (glv_type, model_index, glv_type, n_target, sim_type, ),X_test)

0.6624682963553282
1.0
0.6791672787621973
1.0
0.7459350857561596
1.0
0.7118615889880435
1.0
